import Head from 'next/head'
import { Inter } from 'next/font/google'
import GameContainer from '@/components/core-game/game-container'
import Image from 'next/image'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [target, setTarget] = useState<HTMLElement>();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="main-container relative" ref={(ref) => setTarget(ref as HTMLElement)}>
          { target && 
            (
              <GameContainer 
                target={target}
              />
            )
          }
          <div className="relative z-10 min-h-[400em]">
            <h1>
              Portfolio!
            </h1>
            <div className="min-h-[50em]">
              <p className="mb-[50em]">Some stuff</p>
              <Image
                src="/assets/alienbusters.png"
                alt="test image"
                width={400}
                height={400}
              />
              <p className="mb-[50em]">Some more stuff stuff</p>
            </div>
            <Image
              src="/assets/alienbusters.png"
              alt="test image"
              width={400}
              height={400}
            />
          </div>
        </div>
      </main>
    </>
  )
}
