import Head from 'next/head'
import { Inter } from 'next/font/google'
import GameContainer from '@/components/game/game-container'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="main-container">
          <GameContainer />
          <div>
            <h1>
              Portfolio!
            </h1>
            <Image
              src="/assets/alienbusters.png"
              alt="test image"
              width={400}
              height={400}
            />
          </div>
        </div>
      </main>
    </>
  )
}
